name: CI/CD Pipeline for Python App

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with unittest
        run: |
          python -m unittest test_app.py

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: izar8787/projeto-ci-cd-api-tarefas:latest,izar8787/projeto-ci-cd-api-tarefas:${{ github.run_number }}
          provenance: false

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    environment: production

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Deploy to AWS Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Instala o Docker e Docker Compose (caso ainda não esteja instalado)
            sudo apt-get update
            sudo apt-get install -y docker.io docker-compose

            # Adiciona o usuário 'ubuntu' ao grupo do docker para rodar sem 'sudo'
            sudo usermod -aG docker ${{ secrets.SSH_USER }}

            # Puxa a versão mais recente da imagem do Docker Hub
            docker pull izar8787/projeto-ci-cd-api-tarefas:latest

            # Copia o docker-compose.yml para o servidor
            cat docker-compose.yml > ~/docker-compose.yml

            # Executa a aplicação usando o Docker Compose em modo detached
            docker-compose -f ~/docker-compose.yml up -d
