name: CI/CD Pipeline for Python App

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with unittest
        run: |
          python -m unittest test_app.py

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/projeto-ci-cd-api-tarefas:latest,${{ secrets.DOCKERHUB_USERNAME }}/projeto-ci-cd-api-tarefas:${{ github.run_number }}
          provenance: false

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    environment: production
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Deploy to Cloud
        run: |
          echo "Iniciando o deploy..."
          # Adicione aqui os comandos para fazer o deploy na sua nuvem de escolha
          echo "Deploy concluído!"
